import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'
import Testing from '../components/Testing'
import Testo from '../components/Testo'
import ResponsiveGridTest from '../components/ResponsiveGridTest'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { HamburgerIcon, AddIcon, ExternalLinkIcon, RepeatIcon, EditIcon } from '@chakra-ui/icons'
import { HStack, Center, Flex, VStack, SimpleGrid, IconButton , Grid, Box, Menu, MenuButton, MenuList, MenuItem } from '@chakra-ui/react'

import OdeTiga from '../guys/3-i-dewa-gede-partha-adhi-wiguna'
import RubyEmpatBelas from '../guys/14-ida-bagus-ruby-agastya'
import SilvioEmpat from '../guys/4-i gede silvio-ananda-pinandito-bmm'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sakura 8G</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Center>
      <SimpleGrid columns={[1, null, 3]} spacing='40px' p={3}>

        {/* Team Group */}

    <OdeTiga />
    <RubyEmpatBelas />
    <SilvioEmpat />
    
      </SimpleGrid>
      </Center>
      <br></br>
    <Footer />
    </div>
  )
}
